# Generated by Django 4.1.7 on 2023-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="cafe_imagens/"),
        ),
        migrations.AlterField(
            model_name="cafe",
            name="ingredientes",
            field=models.CharField(max_length=100),
        ),
    ]
