# Generated by Django 4.1.7 on 2023-03-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ingrediente_cafe_data_criacao_cafe_disponivel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cafe",
            name="ingrediente",
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="cafe",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingrediente",
                to="core.cafe",
            ),
            preserve_default=False,
        ),
    ]
