# Generated by Django 4.1.7 on 2023-03-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_cafe_ingrediente_ingrediente_cafe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingrediente",
            name="cafe",
        ),
    ]
