# Generated by Django 4.1.7 on 2023-03-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_ingrediente_cafe"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="ingrdiente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredientes",
                to="core.ingrediente",
            ),
            preserve_default=False,
        ),
    ]
