# Generated by Django 4.1.7 on 2023-03-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_cafe_ingrdiente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cafe",
            name="ingredientes",
        ),
    ]
