# Generated by Django 4.1.7 on 2023-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_cafe_ingredientes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/cafe_imagens/"
            ),
        ),
    ]
