# Generated by Django 4.1.7 on 2023-03-17 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_cafe_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testemunhos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("texto", models.TextField()),
                ("disponivel", models.BooleanField(default=False)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="cafe",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="cafe_images/"),
        ),
    ]
