# Generated by Django 4.1.7 on 2023-03-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_testemunhos_alter_cafe_imagem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Testemunhos",
            new_name="Testemunho",
        ),
    ]
