# Generated by Django 4.1.7 on 2023-03-18 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_contatenos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sobremesas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="sobremesas/"),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=6)),
                ("disponivel", models.BooleanField(default=False)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
